# kubernetes/security/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loyalty-batch-engine-role
  namespace: loyalty-system
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loyalty-batch-engine-role-binding
  namespace: loyalty-system
subjects:
  - kind: ServiceAccount
    name: loyalty-batch-engine
    namespace: loyalty-system
roleRef:
  kind: Role
  name: loyalty-batch-engine-role
  apiGroup: rbac.authorization.k8s.io