apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-secrets-provider
spec:
  provider: vault
  parameters:
    vaultAddress: "http://127.0.0.1:8200"
    roleName: "loyalty-batch-engine"
    objects: |
      - objectName: "postgres-credentials"
        secretPath: "secret/data/loyalty-batch-engine/database"
        secretKey: "credentials"