# kubernetes/deployments/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-batch-engine
  namespace: loyalty-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-batch-engine
  template:
    metadata:
      labels:
        app: loyalty-batch-engine
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-database: "secret/loyalty-batch-engine/database"
        vault.hashicorp.com/role: "loyalty-batch-engine"
    spec:
      serviceAccountName: loyalty-batch-engine
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: loyalty-batch-engine
          image: localhost/loyalty-batch-engine:1.0.0
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: loyalty-batch-engine-config
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DATABASE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: postgres-secrets-provider