# kubernetes/vault/vault-config.yaml
apiVersion: vault.banzaicloud.com/v1alpha1
kind: Vault
metadata:
  name: vault
spec:
  size: 1
  image: vault:1.13.3
  bankVaultsImage: ghcr.io/banzaicloud/bank-vaults:latest

  # Vault configuration
  config:
    storage:
      file:
        path: "/vault/file"
    listener:
      tcp:
        address: "0.0.0.0:8200"
        tls_disable: true
    api_addr: http://127.0.0.1:8200

  # Vault operator configuration
  vaultConfig:
    policies:
      - name: loyalty-batch-engine
        rules: |
          path "secret/data/loyalty-batch-engine/*" {
            capabilities = ["read"]
          }

    auth:
      - type: kubernetes
        roles:
          - name: loyalty-batch-engine
            bound_service_account_names: ["loyalty-batch-engine"]
            bound_service_account_namespaces: ["loyalty-system"]
            policies: ["loyalty-batch-engine"]
            ttl: 1h